test with feature branch

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,12 +1,39 @@
 ---
-version: 2.1
-orbs:
-  node: circleci/node@3.0.0
+version: 2
+jobs:
+  node/test:
+    docker:
+    - image: cimg/node:13.11.0
+    steps:
+    - checkout
+    - run:
+        command: |
+          if [ ! -f "package.json" ]; then
+            echo
+            echo "---"
+            echo "Unable to find your package.json file. Did you forget to set the app-dir parameter?"
+            echo "---"
+            echo
+            echo "Current directory: $(pwd)"
+            echo
+            echo
+            echo "List directory: "
+            echo
+            ls
+            exit 1
+          fi
+        name: Checking for package.json.
+        working_directory: ~/project
+    - run:
+        command: npm run test
+        name: Run NPM Tests
+        working_directory: ~/project
 workflows:
   node-tests:
     jobs:
-      - node/test:
-          filters:
-                branches:
-                  only:
-                    - feature/devops
+    - node/test:
+        filters:
+          branches:
+            only:
+            - feature/devops
+  version: 2
